defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost

production:
  <<: *defaults
  database: dpcontests_dev

development:
  <<: *defaults
  database: dpcontests_dev

test:
  <<: *defaults
  database: dpcontests_test
